# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise – MPN(5ce48873-cc04-4cd4-8c85-2478d6164601)'
    subscriptionId: '5ce48873-cc04-4cd4-8c85-2478d6164601'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'dbarob2'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'deployres1'
